---
title: DANOVA on regional mean densities of maximum temperature in Vietnam
vignette: >
  %\VignetteIndexEntry{DANOVA on regional mean densities of maximum temperature in Vietnam}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
lightbox: true
toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dpi = 300,
  fig.height = 10,
  fig.width = 15,
  fig.ext = "jpg",
  dev = "jpeg",
  dev.args = list(bg = "white")
)
```

```{r setup, message = FALSE}
library(dda)
library(fda.usc)
library(tidyverse)
library(boot)
library(sf)
set.seed(10983)
```

# Preprocessing into density data

```{r preprocessing_mpl, eval = FALSE}
data(vietnam_temperature)
vietnam_temperature_dd <- vietnam_temperature |>
  filter(year %in% selected_years) |>
  mutate(period = if_else(year >= 2000, "2014-2016", "1987-1989")) |>
  mutate(t_max = as_dd(t_max, lambda = 10, nbasis = 10, mc.cores = 15))
```

```{r preprocessing_hist}
data(vietnam_temperature_dd)
data(vietnam_regions)
data(vietnam_provinces)

selected_years <- c(1987:1989, 2014:2016)

vnt <- vietnam_temperature_dd |>
  filter(year %in% selected_years) |>
  mutate(period = if_else(year >= 2000, "2014-2016", "1987-1989")) |>
  group_by(region, province, period) |>
  summarise(t_max = list(c(mean(t_max)))) |>
  ungroup() |>
  left_join(vietnam_regions, by = c("region" = "code")) |>
  rename(region_name = name) |>
  arrange(region, province, period)
class(vnt$t_max) <- c("ddl", "fdl", "list")

vnt |> plot_funs(t_max, color = region_name) +
  facet_grid(vars(period), vars(region_name)) +
  labs(
    title = "Density of maximum temperature per province",
    x = "Temperature (deg. Celsius)",
    y = "Mean density",
    color = "Region"
  )

vnt |> plot_funs(t_max, color = region_name) +
  facet_wrap(vars(period)) +
  labs(
    title = "Density of maximum temperature per province",
    x = "Temperature (deg. Celsius)",
    y = "Mean density",
    color = "Region"
  )
```

# Exploratory analysis by region

```{r regions_map}
vietnam_provinces |>
  left_join(vietnam_regions, by = c("region" = "code")) |>
  rename(region_name = name) |>
  ggplot(aes(fill = region_name)) +
  geom_sf() +
  theme_minimal() +
  labs(x = "Longitude", y = "Latitude", fill = "Region")
```


```{r regional_means}
vntr <- vnt |>
  select(!province) |>
  nest_by(period, region, region_name, .key = "t_max") |>
  mutate(t_max = list(c(mean(t_max[[1]]))))
class(vntr$t_max) <- c("ddl", "fdl", "list")

vntr |> plot_funs(t_max, color = region_name) + facet_wrap(vars(period)) +
  labs(
    title = "Mean density of maximum temperature per region",
    x = "Temperature (deg. Celsius)",
    y = "Mean density",
    color = "Region"
  )
```

```{r lr_plots}
```

# Preliminary study: homogeneity of variances

```{r variance_homogeneity}
vnt_per <- vnt |> filter(period == "2014-2016" & region == "MDR")
plot(as.fd(vnt_per$t_max))

vnt_var <- var.fd(c(as.fd(vnt_per$t_max)))

tt <- seq(
  vnt_var$sbasis$rangeval[1],
  vnt_var$sbasis$rangeval[2],
  length.out = 401
)

z <- eval.bifd(tt, tt, vnt_var) # Covariance
z <- cor.fd(tt, c(as.fd(vnt_per$t_max))) # Correlation

df <- data.frame(
  x = rep(tt, each = length(tt)),
  y = rep(tt, times = length(tt)),
  z = as.vector(z)
)

ggplot(df, aes(x = x, y = y, z = z)) +
  geom_contour_filled() +
  labs(
    title = "Correlation function within the MDR region (2014-2016)",
    fill = "Correlation",
    x = "Temperature (deg. Celsius)", y = "Temperature (deg. Celsius)"
  ) +
  theme_minimal()
```

# DANOVA on the regional mean densities of temperature

## Pointwise F-test

```{r pointwise}
vnte <- vnt |>
  mutate(t_max = as.fd(t_max)) |>
  eval_funs(t_max, n = 1401) |>
  nest_by(across(-c(x, y, id))) |>
  group_by(period)

f_statistic <- function(vnte, indices = NULL) {
  if (!is.null(indices)) vnte$data <- vnte$data[indices]

  vnte |>
    unnest(data) |>
    group_by(period, x, region) |>
    mutate(mean = mean(y), var = (n() - 1) / n() * var(y)) |>
    group_by(period, x) |>
    summarise(F = (n() - 1) / n() * var(mean) / mean(var) * (n() - length(unique(region))) / (length(unique(region)) - 1), .groups = "drop_last")
}

f_statistic(vnte) |>
  ggplot(aes(x, F)) +
  geom_line() +
  geom_hline(yintercept = qf(0.95, 5, 57), color = "red", linetype = "dashed") +
  labs(
    title = "Pointwise F-statistic",
    x = "Temperature (deg. Celsius)",
    yintercept = "Critical value"
  ) +
  facet_grid(rows = vars(period))
```

## Global $F_\text{max}$ and GPF tests

```{r global}
f_max_statistic <- function(vnte, indices = NULL) {
  f_statistic(vnte, indices) |>
    summarise(
      F_max = max(F),
      GPF = integrate(approxfun(x, F), min(x), max(x))$value
    ) |>
    pivot_longer(!period, names_to = "statistic")
}

f_max_statistic(vnte)

if (file.exists("DANOVA.RData")) {
  load("DANOVA.RData")
} else {
  system.time(
    f_max_dist <- boot(vnte,
      function(vnte, indices) f_max_statistic(vnte, indices)$value,
      R = 5000,
      parallel = "multicore",
      ncpus = parallel::detectCores() - 1
    )$t
  )

  f_max_dist <- f_max_statistic(vnte) |>
    slice(rep(seq_len(n()), nrow(f_max_dist))) |>
    mutate(value = c(t(f_max_dist)))

  save(f_max_dist, file = "DANOVA.RData")
}

ival <- vnt_var$sbasis$rangeval
vnt_var <- var.fd(c(as.fd(vnt$t_max)))
tt <- seq(
  ival[1],
  ival[2],
  length.out = 1401
)
z <- eval.bifd(tt, tt, vnt_var) # Covariance
z <- cor.fd(tt, c(as.fd(vnt$t_max))) # Correlation

tr_cov2 <- sum(diag(z %*% z))
beta_w <- diff(ival) / 1401^2 * tr_cov2 / (6 - 1)
d_w <- (6 - 1) * 1401^2 / tr_cov2


f_max_dist |> ggplot(aes(value, linetype = statistic)) +
  geom_density() +
  geom_function(fun = ~ 1 / beta_w * dchisq(.x / beta_w, d_w), color = "red", linetype = "dotted") +
  labs(y = "density") +
  facet_wrap(vars(period))

f_max_dist |>
  group_by(period, statistic) |>
  summarise(quantile(value, 0.95), .groups = "drop") |>
  mutate(value = f_max_statistic(vnte)$value) |>
  select(period, statistic, value, `quantile(value, 0.95)`)
```

# DANOVA on the regional mean negative perturbations between 1987-1989 and 2014-2016

## Pointwise F-test

```{r change_pointwise}
library(fdANOVA)

vnte <- vnt |>
  filter(period == "1987-1989") |>
  mutate(t_max = as.fd(t_max)) |>
  eval_funs(t_max, n = 1401) |>
  select(province, x, y) |>
  pivot_wider(names_from = province, values_from = y) |>
  column_to_rownames("x")

plotFANOVA(vnte, vietnam_provinces$region, separately = TRUE)

system.time(
  res <- fanova.tests(vnte, vietnam_provinces$region, params = list(
    paramFP = list(B.FP = 100, basis = "b-spline"),
    paramCH = 100,
    paramCS = 100,
    paramL2b = 100,
    paramFb = 100,
    paramFmaxb = 100,
    paramTRP = list(B.TRP = 100)
  ), parallel = TRUE, nslaves = parallel::detectCores() - 1)
)
save(res, file = "DANOVA.RData")
```

## Global $F_\text{max}$ and GPF tests

```{r change_global}

```
