---
title: "density_estimation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{density_estimation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
```

```{r mean_by_region}
library(tidyverse)
data(vietnam_temperature)
data(vietnam_regions)

selected_year <- 1987

temp <- vietnam_temperature |>
  filter(year == selected_year) |>
  dplyr::group_by(region)

smooth <- function(...) {
  dd$new(
    rangeval = c(-5, 45),
    lambda = 1e-1, nbasis = 30, ...
  )
}
mean_by_region <- temp |>
  mutate(t_max_dd = lapply(t_max, smooth)) |>
  summarize(mean = list(mean_dd(unlist(t_max_dd))))

par(mfrow = c(2, 3))
for (i in 1:6) {
  plot(mean_by_region$mean[[i]],
    xlab = "Temperature (°C)",
    ylab = vietnam_regions[vietnam_regions$code == mean_by_region$region[i], "name"]
  )
}
title(paste("Temperature Densities in Vietnam by Region in", selected_year),
  line = -2, outer = TRUE
)

# Total mean
mean_dd(mean_by_region$mean)
```
