---
title: "dICS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dICS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{tidyverse}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dda)
library(tidyverse)
library(GGally)
```

```{r preprocessing}
data(vietnam_temperature)
selected_years <- 2013:2016

temps <- vietnam_temperature |>
  filter(year %in% selected_years) |>
  filter(region %in% c("NMM", "RRD") | province %in% c("ANGIANG", "BACLIEU")) |>
  arrange(region, province) |>
  group_by(region)

nknots <- 6
breaks <- quantile(unlist(temps$t_max), seq(0, 1, 1 / (nknots + 1)))

smooth <- function(...) {
  density(
    basis = fda::create.bspline.basis(breaks = breaks),
    lambda = 1,
    ...
  )
}

temps <- temps |> mutate(t_max_dd = lapply(t_max, smooth))
t_max <- dda:::merge.dd(temps$t_max_dd)
plot(t_max[33])
```

```{r ics}
t_max_ics <- ICS(t_max, center = TRUE)
plot(t_max_ics$gen_kurtosis)
ggpairs(as.data.frame(t_max_ics$scores),
  diag = "blank",
  columns = c(1:3, 8:9),
  aes(label = seq_len(nrow(temps)), color = temps$region, shape = NA)
) + geom_text()
plot(t_max_ics$W)
plot(ICSOutlier::ics_distances(t_max_ics, index = 1:3))
plot(ICSOutlier::ics_distances(t_max_ics))
```

```{r checks}
all(round(fda::inprod(t_max, t_max_ics$W) - t_max_ics$scores, 2) == 0)
```

```{r ics_outlier}
t_max_out <- ICS_outlier(t_max, verbose = TRUE)
plot(t_max_out)
plot(t_max) + scale_color_manual(values = t_max_out$outliers + 1)
fda::plot.fd(t_max, col = t_max_out$outliers + 1)
```
