---
title: "ICS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ICS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{tidyverse}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dda)
library(tidyverse)
library(GGally)
```

```{r preprocessing}
data(vietnam_temperature)
selected_years <- 2013:2016

system.time(
  vnt <- vietnam_temperature |>
    filter(year %in% selected_years) |>
    filter(region %in% c("NMM", "RRD") | province %in% c("ANGIANG", "BACLIEU")) |>
    arrange(region, province) |>
    mutate(across(c(t_min, t_max), \(x) as_dd(x, lambda = 1, nbasis = 18, mc.cores = 16)))
)

vnt |> plot_funs(t_max, color = region)
```

```{r ics}
t_max_ics <- ICS(vnt$t_max, center = TRUE)
plot(t_max_ics$gen_kurtosis)

ggpairs(as.data.frame(t_max_ics$scores),
  diag = "blank",
  columns = c(1:3, 8:9),
  aes(label = seq_len(nrow(vnt)), color = vnt$region, shape = NA)
) + geom_text()
```

```{r inprod}
t_max_out <- ICS_outlier(vnt$t_max)
ICS_outlier(as.fd(vnt$t_max), index = 1:4)
```

```{r checks}
x <- ddobj
x_ics <- ICS(x)
error <- inprod(c(x), x_ics$H) - x_ics$scores
max(error)

x_ics <- ICS(x, slow = TRUE)
error <- inprod(c(x), x_ics$H) - x_ics$scores
max(error)

x_ics <- ICS(x, center = TRUE)
error <- inprod(c(center(x)), x_ics$H) - x_ics$scores
max(error)

x_ics <- ICS(x, center = TRUE, slow = TRUE)
error <- inprod(c(center(x)), x_ics$H) - x_ics$scores
max(error)
```

```{r reconstructing}
x <- ddobj
basisobj <- x$basis
p <- basisobj$nbasis
x_mean <- c(mean(x))
x_ics <- ICS(x, center = TRUE, slow = TRUE)
h_dual <- to_zbsplines(x_ics$H_dual)
h <- to_zbsplines(x_ics$H)
all(round(inprod(x_ics$H, x_ics$H_dual), 2) == diag(p - 1))

x_rec <- to_zbsplines(
  inv = TRUE,
  coefs = t(x_ics$scores %*% t(h_dual)),
  basis = basisobj,
)
x_rec <- x_rec |> sweep(1, x_mean$coefs, "+")
x_rec <- dd(clr = fd(coef = x_rec, basisobj = basisobj))

error <- c(x) - x_rec
print(max(error$coefs))
```

```{r gaussian-coefs}
library(mvnfast)

coefs <- rbind(
  rmvn(5, mu = c(10, rep(0, 3)), sigma = diag(4)),
  rmvn(95, mu = rep(0, 4), sigma = diag(4))
)

basisobj <- create.bspline.basis(nbasis = 4)

ddobj <- dd(clr = fd(t(coefs), basisobj))

plot(ICS_outlier(ddobj))
plot(ICS_outlier(as.fd(ddobj, slow = TRUE)))
```


```{r inprod-vs-integrate}
p <- dd(vietnam_temperature$t_max[[2]])

cat("\n")
ival <- p$basis$rangeval

integrate(\(t) eval.fd(p, t), ival[1], ival[2])
inprod(p)

bspint <- inprod(p$basis)
t(bspint) %*% p$coefs
```


We could also work on negative perturbations.


```{r relative}
vnt_present <- vietnam_temperature |>
  rename(year_present = year, t_max_present = t_max) |>
  arrange(region, province, year_present)

vnt_past <- vietnam_temperature |>
  rename(year_past = year, t_max_past = t_max) |>
  arrange(region, province, year_past)

intersect_range <- function(vec, range) {
  vec[vec >= range[1] & vec <= range[2]]
}

vnt <- vnt_present |>
  select(region, province, year_present, t_max_present) |>
  left_join(vnt_past, c("region", "province"), relationship = "many-to-many") |>
  filter(year_present - year_past == 9) |>
  mutate(across(
    c(t_max_present, t_max_past),
    function(x) {
      as_dd(x,
        full_sample = intersect_range(c(unlist(t_max_present), unlist(t_max_past)), c(-10, 360)),
        knots_pos = "quantiles",
        lambda = 2, nbasis = 14, mc.cores = 15
      )
    }
  )) |>
  group_by(region, province)

vnt |>
  summarise(t_max_diff = list(gmean(c(relative(t_max_present, t_max_past)))))

vnt |> plot_funs(t_max_diff, color = province) +
  facet_wrap(vars(region))

vnt |> plot_funs(t_max_diff, rangeval = c(8, 42), color = province) +
  facet_wrap(vars(region)) +
  geom_hline(yintercept = 1 / diff(vnt$t_max_diff[[1]]$basis$rangeval))
```
