---
title: Outlier detection using ICS and climate change in Vietnam (JES 2024 edition)
vignette: >
  %\VignetteIndexEntry{Outlier detection using ICS and climate change in Vietnam (JES 2024 edition)}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
lightbox: true
toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dpi = 300,
  fig.height = 10,
  fig.width = 15,
  fig.ext = "jpg",
  dev = "jpeg",
  dev.args = list(bg = "white")
)
```

```{r setup, message = FALSE}
library(dda)
library(tidyverse)
library(sf)

theme_set(theme_minimal(base_size = 18))
theme_legend_inside <- theme(
  legend.position = "inside",
  legend.position.inside = c(.05, .95),
  legend.justification = c("left", "top"),
  legend.box.just = "left",
  legend.margin = margin(6, 6, 6, 6)
)
theme_legend_inside_right <- theme(
  legend.position = "inside",
  legend.position.inside = c(.95, .95),
  legend.justification = c("right", "top"),
  legend.box.just = "right",
  legend.margin = margin(6, 6, 6, 6)
)
```

# Northern regions and 2 provinces from the South

```{r vnt_north_south_map}
data(vietnam_provinces)
data(vietnam_regions)

vietnam_regions$name <- c(
  "Nord", "Cote centrale", "Montagnes centrales", "Sud-est", "Delta du Mekong", "Delta du Fleuve Rouge"
)

vietnam_provinces |>
  mutate(province = if_else(region %in% c("NMM", "RRD") | province %in% c("HOCHIMINH", "DONGNAI"), province, NA)) |>
  left_join(vietnam_regions, by = c("region" = "code")) |>
  select(!region) |>
  rename(region = name) |>
  ggplot(aes(fill = region, label = province)) +
  geom_sf() +
  geom_sf_label(fill = "white", size = 3) +
  scale_x_continuous(breaks = seq(from = -180, to = 180, by = 2)) +
  labs(x = "longitude", y = "latitude")
```

```{r vnt_north_south}
# Filter the data set
data(vietnam_temperature)
selected_years <- 2013:2016

vnt <- vietnam_temperature |>
  filter(year %in% selected_years) |>
  filter(region %in% c("NMM", "RRD") | province %in% c("HOCHIMINH", "DONGNAI")) |>
  left_join(vietnam_regions, by = c("region" = "code")) |>
  select(!region) |>
  rename(region = name) |>
  arrange(region, province)

vnts <- vnt |>
  mutate(t_max = as_dd(t_max,
    lambda = 1, nbasis = 12, mc.cores = 12
  ))

vnts |>
  plot_funs(t_max, color = region) +
  theme_legend_inside +
  labs(x = "temperature (deg. Celsius)", y = "densite")

vnts |>
  mutate(t_max = as.fd(center(t_max))) |>
  plot_funs(t_max, color = region) +
  theme_legend_inside + theme(legend.position.inside = c(.1, .95)) +
  labs(x = "temperature (deg. Celsius)", y = "clr(densite) centree")
```

# 30 years, 1 climate region (10 provinces)

```{r climate_regions_map}
vietnam_provinces <- vietnam_provinces |>
  arrange(region, province) |>
  mutate(climate_region = case_when(
    province %in% c("LAICHAU", "DIENBIEN", "SONLA") ~ "S1",
    province %in% c(
      "LAOCAI", "YENBAI", "HAGIANG", "CAOBANG", "TUYENQUANG",
      "BACKAN", "THAINGUYEN", "LANGSON", "BACGIANG", "QUANGNINH"
    ) ~ "S2",
    region %in% c("NMM", "RRD") ~ "S3",
    .default = NA
  ))

vietnam_provinces |>
  filter(region %in% c("RRD", "NMM")) |>
  ggplot(aes(fill = climate_region, label = province)) +
  geom_sf() +
  geom_sf_label(fill = "white") +
  labs(x = "longitude", y = "latitude", fill = "region climatique")
```

```{r climate_regions}
data(vietnam_temperature)
data(vietnam_regions)
data(vietnam_provinces)

vntcr <- vietnam_temperature |>
  filter(region %in% c("RRD", "NMM")) |>
  dplyr::select(year, province, t_max) |>
  left_join(vietnam_provinces, by = "province") |>
  st_as_sf() |>
  dplyr::select(year, climate_region, province, t_max) |>
  filter(climate_region == "S2") |>
  arrange(year, province)

vnt <- vntcr |>
  mutate(t_max = as_dd(t_max, lambda = 10, nbasis = 10, mc.cores = 15))
class(vnt$t_max) <- c("ddl", "fdl", "list")

vnt |> plot_funs(t_max, color = province) +
  facet_wrap(vars(year)) + labs(x = "temperature (deg. Celsius)", y = "densite")

icsout <- ICS_outlier(vnt$t_max, index = 1, n_cores = 14)
```

```{r climate_regions_screeplot}
icsout$result |> ggplot(aes(index, gen_kurtosis, group = 1)) +
  geom_line(alpha = 0.5) +
  geom_point(aes(color = selected, size = selected))
```

```{r climate_regions_outliers}
#| fig-width: 7.5
#| fig-height: 5
#| layout-ncol: 2

vnt <- vnt |>
  mutate(
    index = seq_len(nrow(icsout$scores)),
    outlying = as.factor(icsout$outliers),
    distances = icsout$ics_distances
  ) |>
  cbind(icsout$scores)

vnt |>
  mutate(year = ifelse(outlying == 1, year, "non atypique")) |>
  plot_funs(t_max, color = year, alpha = outlying) +
  theme_legend_inside +
  labs(x = "temperature (deg. Celsius)", y = "densite", color = "annee", alpha = "atypique")

vnt |>
  mutate(
    t_max = as.fd(center(t_max)),
    year = ifelse(outlying == 1, year, "non atypique")
  ) |>
  plot_funs(t_max, color = year, alpha = outlying) +
  theme(legend.position = "none") +
  labs(x = "temperature (deg. Celsius)", y = "clr(densite) centree")
```

```{r climate_regions_distances}
#| fig-width: 7.5
#| fig-height: 5

vnt |> ggplot(aes(index, distances, color = province, label = year)) +
  geom_text() +
  theme_legend_inside_right +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  geom_hline(yintercept = icsout$ics_dist_cutoff)
```


```{r climate_regions_scatter}
#| fig-width: 7.5
#| fig-height: 5

vnt |>
  mutate(province = ifelse(outlying == 1, province, "non atypique")) |>
  ggplot(aes(IC.1, IC.2)) +
  theme_legend_inside_right +
  geom_text(aes(color = province, label = year))
```

```{r climate_regions_eigendensities}
#| fig-width: 7.5
#| fig-height: 5
#| layout-ncol: 2

icsout$result |>
  filter(selected) |>
  plot_funs(H_dual, color = index) +
  geom_hline(yintercept = 1 / diff(icsout$result$H_dual[[1]]$basis$rangeval)) +
  theme(legend.position = "none") +
  labs(x = "temperature (deg. Celsius)", y = "densite")

icsout$result |>
  mutate(H_dual = as.fd(H_dual)) |>
  filter(selected) |>
  plot_funs(H_dual, color = index) +
  geom_hline(yintercept = 0) +
  theme(legend.position = "none") +
  labs(x = "temperature (deg. Celsius)", y = "clr(densite)")
```
