---
title: "ICS on temperature distributions in Vietnam, with a grid"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ICS on temperature distributions in Vietnam, with a grid}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(dda)
```

```{r vnt_north_south}
# Filter the data set
data(vietnam_temperature)
selected_years <- 2013:2016

vnt <- vietnam_temperature |>
  filter(year %in% selected_years) |>
  filter(region %in% c("NMM", "RRD") | province %in% c("ANGIANG", "BACLIEU")) |>
  arrange(region, province)

vnt |>
  mutate(t_max = as_dd(t_max,
    lambda = 1, nbasis = 12, mc.cores = 12
  )) |>
  plot_funs(t_max, color = region) +
  theme_minimal() +
  labs(x = "temperature (°C)", y = "density")
```

Let us create a grid of parameters and
define the function to call for each parameter.

```{r ics_grid}
param_grid <- expand.grid(
  knots_pos = "quantiles",
  nknots = 7,
  lambda = 10^c(0, 5)
)

smooth_ICS <- function(knots_pos, nknots, lambda) {
  vnts <- vnt |>
    mutate(t_max = as_dd(t_max,
      lambda = lambda, nbasis = 5 + nknots, mc.cores = 12, knots_pos = knots_pos
    ))
  knots_pos_str <- ifelse(knots_pos == "quantiles",
    "Knots at quantiles", "Equally spaced knots"
  )
  print(paste(
    "# of knots:", nknots, "|",
    "log10(lambda):", log10(lambda), "|",
    knots_pos_str
  ))

  list(
    dd = vnts$t_max,
    ics = tryCatch(ICS(as.fd(vnts$t_max)), error = function(e) e),
    ics_out = tryCatch(ICS_outlier(as.fd(vnts$t_max),
      n_cores = 12, index = 1:4
    ), error = function(e) e)
  )
}

# Smooth and detect outliers for each parameter
system.time(
  ics_grid <- param_grid |>
    mutate(id = seq_len(n())) |>
    rowwise() |>
    mutate(res = list(smooth_ICS(knots_pos, nknots, lambda)))
)
save(ics_grid, file = "ICS_grid.RData")
```

```{r ics_grid_out}
load("ICS_grid.RData")

ics_out <- ics_grid |>
  rowwise() |>
  filter(!(any(class(res$ics_out) == "error"))) |>
  mutate(res = list(as.factor(res$ics_out$outliers))) |>
  rename(outliers = res) |>
  unnest_longer(outliers, indices_to = "obs_id")

ics_out |> ggplot(aes(log10(lambda), obs_id, fill = outliers)) +
  geom_tile() +
  scale_fill_grey(start = 1, end = 0) +
  facet_grid(cols = vars(nknots), rows = vars(knots_pos))
```

```{r details, eval = FALSE}
library(dda)

res <- ics_grid |>
  filter(nknots < 10) |>
  #  filter(nknots == 45 & lambda == 10 & knots_pos == "eq_spaced") |>
  filter(nknots == 4 & lambda == 1e8 & knots_pos == "quantiles") |>
  sample_n(1)


ics_out1 <- res$res[[1]]$ics_out

ics_out2 <- ICS_outlier(as.fd(res$res[[1]]$dd), index = 1:4, n_cores = 14)
all(ics_out1$outliers == ics_out2$outliers)
plot(ics_out1)

qr(cov(t(to_zbsplines(c(res$res[[1]]$dd)))))
eigen(cov(t(to_zbsplines(c(res$res[[1]]$dd)))))$values
```

```{r eval = FALSE}
ics_out |>
  filter(outliers == 1) |>
  group_by(obs_id) |>
  summarise(n = n() / nrow(ics_grid)) |>
  ggplot(aes(obs_id, n)) +
  geom_bar(stat = "identity")

tab <- ics_out |> pivot_wider(names_from = obs_id, values_from = outliers)
tab <- apply(tab[, c(5:116)], c(1, 2), as.numeric)
library(corrplot)
corrplot(cor(tab))
```


