---
title: "Spanish Weather"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Spanish Weather}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{fda.usc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dda)
library(fda.usc)
library(ggplot2)
library(GGally)
```

```{r preprocessing}
data(aemet)
temps <- aemet$temp
str(temps)

plot(density(temps$data[1, ], method = "kernel"))
plot(density(temps$data[1, ], nbasis = 10, lambda = 1))

nknots <- 24
knots <- quantile(temps$data, seq(0, 1, 1 / nknots))

smooth <- function(...) {
  density(
    basis = fda::create.bspline.basis(breaks = knots),
    lambda = 1e-1,
    ...
  )
}

temps <- dda:::merge.dd(as.list(apply(temps$data, 1, smooth)))
plot(temps)
```

```{r ics}
temps_ics <- ICS(temps)
plot(temps_ics$W)
ggpairs(as.data.frame(temps_ics$scores),
  diag = "blank",
  columns = c(1:3, 22:25),
  aes(label = seq_len(ncol(temps$coefs)))
) + geom_text()
```

```{r ics_outlier}
temps_out <- ICS_outlier(temps)
plot(temps_out)
plot(temps) + scale_color_manual(values = temps_out$outliers + 1)
plot.fd(temps[temps_out$outliers == 1], col = "black")
fda:::lines.fd(mean(temps), col = "green")
plot.fd(temps, col = temps_out$outliers + 1)
```

```{r zbsplines_checks}
bfd <- fd(basisobj = temps$basis)
bfd$coefs <- to_zbsplines(basis = bfd$basis, inv = TRUE)
inprod(bfd)
plot(bfd)

a <- to_zbsplines(basis = bfd$basis, inv = TRUE)
a_inv <- to_zbsplines(basis = bfd$basis)
all(round(a %*% a_inv %*% temps$coefs - temps$coefs, 3) == 0)
all(round(a_inv %*% a, 14) == diag(bfd$basis$nbasis - 1))
```
