---
title: "ANOVA on distributional data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ANOVA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dda)
library(fda.usc)
library(tidyverse)
data(vietnam_temperature)
data(vietnam_regions)
```

```{r preprocessing}
selected_years <- c(1987:1989, 2014:2016)

vnt <- vietnam_temperature |>
  filter(year %in% selected_years) |>
  mutate(period = if_else(year >= 2000, "Present", "Past")) |>
  mutate(t_max = as_dd(t_max, lambda = 10, nbasis = 10, mc.cores = 15)) |>
  group_by(region, province, period) |>
  summarise(t_max = list(c(mean(t_max)))) |>
  ungroup() |>
  left_join(vietnam_regions, by = c("region" = "code")) |>
  rename(region_name = name) |>
  arrange(region, province, period)
class(vnt$t_max) <- c("ddl", "fdl", "list")

vntr <- vnt |>
  select(!province) |>
  nest_by(period, region, region_name, .key = "t_max") |>
  mutate(t_max = list(c(mean(t_max[[1]]))))
class(vntr$t_max) <- c("ddl", "fdl", "list")

vntr |> plot_funs(t_max, color = region_name) + facet_wrap(vars(period))
```

```{r covariance}
vnt_per <- vnt |> filter(period == "Past" & region == "MDR")
plot(as.fd(vnt_per$t_max))

vnt_var <- var.fd(c(as.fd(vnt_per$t_max)))
tt <- seq(vnt_var$sbasis$rangeval[1], vnt_var$sbasis$rangeval[2], length.out = 400)

z <- cor.fd(tt, c(as.fd(vnt_per$t_max)))
z <- eval.bifd(tt, tt, vnt_var)
df <- data.frame(
  x = rep(tt, each = length(tt)),
  y = rep(tt, times = length(tt)),
  z = as.vector(z)
)
ggplot(df, aes(x = x, y = y, z = z)) +
  geom_contour_filled() +
  labs(title = "Filled Contour Plot", fill = "Legend") +
  theme_minimal()
```

```{r group_by_region}
vn_temp_region <- vn_temp |>
  group_by(period, region) |>
  summarize(
    t_max_mean = mean.dd(t_max),
    t_max_gmean = gmean.dd(t_max)
  )

# Aitchison means by region
vn_temp_region |> plot_funs(t_max_mean, color = region) +
  facet_grid(rows = vars(period)) +
  labs(x = "Temperature (°C)", y = "Yearly density") +
  # Set plot title
  ggtitle("Average density of temperature by region")

# Means by region and total: clr
vn_temp_region |> plot_funs(t_max_gmean, color = region) +
  facet_grid(rows = vars(period)) +
  labs(x = "Temperature (°C)", y = "Geometric mean") +
  # Set plot title
  ggtitle("Geometric mean of temperature densities by region")
```

```{r lr_plots}
```

```{r f-test}
vn_temp_ftest <- vn_temp |>
  eval_funs(t_max, n = 401) |>
  nest_by(period, x) |>
  mutate(ftest = anova(lm(y ~ region, data))$F[1])

vn_temp_ftest |>
  ggplot(aes(x, ftest)) +
  geom_line() +
  facet_grid(rows = vars(period))

vn_temp_ftest <- vn_temp |>
  eval_funs(t_max, n = 401) |>
  group_by(x, region) |>
  mutate(within = (y - mean(y))^2 / (n() - 6))
```


```{r t-test}

```


