# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib dda, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_dda__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_dda__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`density_fd_rust_raw` <- function(`x`, `f`, `basis_kind`, `nbasis`, `range`, `knots`, `norder`, `params`, `cvec0`, `zmat`, `zmat_rows`, `kmat`, `conv`, `iterlim`, `climit_lo`, `climit_hi`) {
  .Call(savvy_density_fd_rust_raw__impl, `x`, `f`, `basis_kind`, `nbasis`, `range`, `knots`, `norder`, `params`, `cvec0`, `zmat`, `zmat_rows`, `kmat`, `conv`, `iterlim`, `climit_lo`, `climit_hi`)
}


