# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dda_wrappers", use_symbols = TRUE, package_name = "dda")

#' @usage NULL
#' @useDynLib dda, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
density_mpl <- function() .Call(wrap__density_mpl)


# nolint end
